name: Deno

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  DENO_FUTURE: 1
jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write # This is required to allow the GitHub Action to authenticate with Deno Deploy.
      contents: read

    steps:
      - name: Clone repo
        uses: actions/checkout@v3

      - name: Install Deno
        uses: denoland/setup-deno@v1

      - name: Install Emscripten SDK
        run: |
          git clone https://github.com/emscripten-core/emsdk.git
          cd emsdk
          ./emsdk install latest
          ./emsdk activate latest
          
      - name: Load EMSDK environment
        run: |
          source emsdk/emsdk_env.sh
          echo "EMSDK=$EMSDK" >> $GITHUB_ENV
          echo "EMSDK_NODE=$EMSDK_NODE" >> $GITHUB_ENV
          echo "PATH=$PATH" >> $GITHUB_ENV

      - name: Build
        run: deno task build

      - name: Deploy to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          args: deploy
        #  project: luthfihakim2004-wasm # the name of the project on Deno Deploy
        #  entrypoint: https://deno.land/std/http/file_server.ts
        #  root: dist
