name: Deno

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  DENO_FUTURE: 1
jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write # This is required to allow the GitHub Action to authenticate with Deno Deploy.
      contents: read

    steps:
      - name: Clone repo
        uses: actions/checkout@v3

      - name: Install Deno
        uses: denoland/setup-deno@v1

      - name: Install and Activate Emscripten SDK
        run: |
          git clone https://github.com/emscripten-core/emsdk.git
          cd emsdk
          ./emsdk install latest
          ./emsdk activate latest
          source ./emsdk_env.sh
          echo "EMSDK=$(pwd)" >> $GITHUB_ENV
          echo "$(pwd)/upstream/emscripten" >> $GITHUB_PATH

      - name: Build
        run: deno task build

      - name: Deploy to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: luthfihakim2004-wasm # the name of the project on Deno Deploy
          entrypoint: ../main.ts
          root: ./
